version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - swagger-service
    links:
      - swagger-service
    ports:
      - 80:80

  swagger-service:
    build:
      context: .
      dockerfile: docker/Dockerfile